### ISSUE TITLE
separate php-fpm and nginx

### ISSUE THREAD

**Issue by Colonizator1** [foerster-werbung/ocb#3]
Hello! Nice repo:)
What about separate php-fpm and nginx? There could be 2 containers instead of one. The benefits:
- web container updates without restarting and losing a single request: for example, if we want to add a new php extension we'll be able to build/run a new web container, change the nginx config, and reload
- separated php/nginx logs
- security: only one opened port on the nginx container, without access to the PHP process
- docker best practice: one process - one container

I'll be glad if you share your thoughts, thx!

**Comment by TimFoerster** [comment]
Thanks for your feedback.

This project/container is for development only and not for production usage. 
Therefore I don't see any benefits for the developer experience to seperate FPM and NGINX.
This container is based on [dwchiang/nginx-php-fpm](https://github.com/dwchiang/nginx-php-fpm). I don't configure either nginx nor php-fpm here.
